# Generated by Django 2.2.7 on 2019-11-20 10:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, default=list, null=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Retros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('meeting_format', models.CharField(blank=True, choices=[('standard', 'STANDARD'), ('other_type', 'OTHER_TYPE')], default='standard', max_length=25, null=True)),
                ('fk_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrospective.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('simple_card', 'SIMPLE'), ('action_item', 'ACTION_ITEM')], max_length=30, null=True)),
                ('is_anonymus', models.NullBooleanField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None)),
                ('status', models.CharField(blank=True, choices=[('DONE', 'done'), ('IN PROGRESS', 'in progress')], max_length=30, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'high'), ('MIDDLE', 'middle'), ('LOW', 'low')], max_length=30, null=True)),
                ('asignee', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), blank=True, default=list, size=None)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('retro_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrospective.Retros')),
            ],
        ),
    ]
